server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
      url: bolt://127.0.0.1:7687
      username: neo4j
      password: jiangbin
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/graph?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql 
#--------七牛云配置
qiniu:
  access:
    key: 2J5BOKpbxDlzkYVYZ5dwGS3jAevVmOJwcL3fIdpw
  secret:
    key: 2LXAQbFFbFR_I76bseNEmu-Sjnh4RRaSRsazX5Dj
  bucket:
    name: nndt
    host:
      name: file.miaoleyan.com
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image\\   linx 格式"/home/blog/image/";
   location : /home/blog/image/
file:
  serverurl:  http://localhost:8089
  location : /home/kgmanager/csv/   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";